### ISSUE TITLE
Naming this language

### ISSUE THREAD

**Issue by Kuinox** [Kuinox/KuiLang#3]
Didn't had any decent idea how to name this language.  
It's up to be changed when we will find a fitting name.

**Comment by teo-tsirpanis** [comment]
The existing name is not a bad one; GitHub just recommended me [another programming language named after its author](https://github.com/perlang-org/perlang). If you go down that way, I recommend to remove the hyphen and titlecase it into __Kuilang__ (with the source files' extension being `.kui`).

**Comment by Kuinox** [comment]
Let's go with that then, it will be one less thing to worry about.
For the extension name, .kl works too, no ?

**Comment by teo-tsirpanis** [comment]
No objections if you like `.kl` better, you decide, and neither seems to be taken by something else.
